import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Topbar from "./components/Topbar";
import Leftsidebar from "./components/Leftsidebar";
import RightSidebar from "./components/RightSidebar";
import Bottombar from "./components/Bottombar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mait-connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div>
            <Topbar />
          </div>
          <div>
            <Leftsidebar />
          </div>
          <main>{children}</main>
          <div>
            <RightSidebar />
          </div>
          <div>
            <Bottombar />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
